version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/moodledb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - MOODLE_URL=https://seu-moodle.example/webservice/rest/server.php
      - MOODLE_TOKEN=SUA_TOKEN_MOODLE
      - SECURITY_JWT_SECRET=MUITO_SECRETO_MUDE_ISTO_256_BITS_MINIMO
      - SECURITY_JWT_EXPIRATION_MS=86400000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: moodledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
